#!/usr/bin/expect
log_user 1
set timeout 10
set username [lindex $argv 0]
set password [lindex $argv 1]

spawn meteor login

expect {
  timeout { send_user "Login failed (no Username prompt).\n"; exit 1 }
  "Username"
}
send $username\n
expect {
  timeout { send_user "Login failed (no Password prompt).\n"; exit 1 }
  "Password"
}
send $password\n

expect "Logged\sin\sas"

lassign [wait] pid spawnid os_error_flag value

exit $value
